const c=document.querySelector('#g'),x=c.getContext('2d');let W,H,dpr,car={x:.5,y:.78,a:Math.PI,s:0},keys={},marks=[],smoke=[],touches=[],lastTap={l:0,r:0},drift=0,driftDir=0,steerHold=0,preset=1,audio=null,tune={speed:1,accel:1,steer:1,grip:1,drift:1,offroad:1};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>keys[e.key]=1);addEventListener('keyup',e=>keys[e.key]=0);
async function startAudio(){if(audio){if(audio.A.state==='suspended')await audio.A.resume();return}let A=new (window.AudioContext||window.webkitAudioContext)();await A.resume();let master=A.createGain();master.gain.value=.32;master.connect(A.destination);let eng=A.createOscillator(),eg=A.createGain();eng.type='sawtooth';eng.frequency.value=75;eg.gain.value=.22;eng.connect(eg).connect(master);eng.start();let noise=A.createBufferSource(),buf=A.createBuffer(1,A.sampleRate*2,A.sampleRate);let d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;noise.buffer=buf;noise.loop=true;let filt=A.createBiquadFilter(),ng=A.createGain();filt.type='bandpass';filt.frequency.value=900;filt.Q.value=.7;ng.gain.value=0;noise.connect(filt).connect(ng).connect(master);noise.start();audio={A,eng,eg,ng,filt}}
function updateAudio(road,st,br){if(!audio)return;let t=audio.A.currentTime,s=Math.max(0,car.s);audio.eng.frequency.setTargetAtTime(65+s*520,t,.04);audio.eg.gain.setTargetAtTime(.14+s*.75,t,.04);let slip=Math.max(drift>0?.65:0,Math.abs(st)*Math.max(0,(s-.11)*2.5),road?0:.22);audio.ng.gain.setTargetAtTime(Math.min(.6,slip),t,.025);audio.filt.frequency.setTargetAtTime(road?1100:430,t,.05)}
function setTouches(e){e.preventDefault();touches=[...e.touches].map(t=>({x:t.clientX,y:t.clientY}))}

c.addEventListener('touchstart',e=>{startAudio();let now=performance.now();for(const t of e.changedTouches){let side=t.clientX<W*.36?'l':t.clientX>W*.64?'r':null;if(side){if(now-lastTap[side]<300){drift=.48;driftDir=side==='l'?-1:1}lastTap[side]=now}}setTouches(e)},{passive:false});c.addEventListener('touchmove',setTouches,{passive:false});c.addEventListener('touchend',setTouches,{passive:false});
function trackPath(){x.beginPath();x.moveTo(W*.27,H*.80);x.lineTo(W*.27,H*.30);x.bezierCurveTo(W*.27,H*.18,W*.36,H*.12,W*.50,H*.12);x.bezierCurveTo(W*.66,H*.12,W*.76,H*.19,W*.76,H*.31);x.lineTo(W*.76,H*.48);x.bezierCurveTo(W*.76,H*.55,W*.69,H*.58,W*.61,H*.58);x.lineTo(W*.47,H*.58);x.bezierCurveTo(W*.38,H*.58,W*.37,H*.66,W*.47,H*.69);x.lineTo(W*.68,H*.75);x.bezierCurveTo(W*.82,H*.79,W*.78,H*.90,W*.63,H*.90);x.lineTo(W*.42,H*.90);x.bezierCurveTo(W*.32,H*.90,W*.27,H*.87,W*.27,H*.80)}
let roadCanvas,roadCtx;function roadMask(){if(!roadCanvas||roadCanvas.width!==W||roadCanvas.height!==H){roadCanvas=document.createElement('canvas');roadCanvas.width=W;roadCanvas.height=H;roadCtx=roadCanvas.getContext('2d');roadCtx.clearRect(0,0,W,H);roadCtx.beginPath();roadCtx.moveTo(W*.27,H*.80);roadCtx.lineTo(W*.27,H*.30);roadCtx.bezierCurveTo(W*.27,H*.18,W*.36,H*.12,W*.50,H*.12);roadCtx.bezierCurveTo(W*.66,H*.12,W*.76,H*.19,W*.76,H*.31);roadCtx.lineTo(W*.76,H*.48);roadCtx.bezierCurveTo(W*.76,H*.55,W*.69,H*.58,W*.61,H*.58);roadCtx.lineTo(W*.47,H*.58);roadCtx.bezierCurveTo(W*.38,H*.58,W*.37,H*.66,W*.47,H*.69);roadCtx.lineTo(W*.68,H*.75);roadCtx.bezierCurveTo(W*.82,H*.79,W*.78,H*.90,W*.63,H*.90);roadCtx.lineTo(W*.42,H*.90);roadCtx.bezierCurveTo(W*.32,H*.90,W*.27,H*.87,W*.27,H*.80);roadCtx.lineWidth=Math.max(42,Math.min(W,H)*.14);roadCtx.strokeStyle='#fff';roadCtx.stroke()}}
function onRoad(){roadMask();return roadCtx.getImageData(Math.max(0,Math.min(W-1,car.x*W))|0,Math.max(0,Math.min(H-1,car.y*H))|0,1,1).data[3]>0}
function controls(){let st=(keys.ArrowLeft?-1:0)+(keys.ArrowRight?1:0);for(const t of touches){if(t.x<W*.5)st-=1;else st+=1}return{st:Math.max(-1,Math.min(1,st)),gas:1,br:0}}
function draw(){let road=onRoad();x.fillStyle='#090615';x.fillRect(0,0,W,H);x.save();x.shadowBlur=22;x.shadowColor='#ff2fa8';trackPath();x.lineWidth=Math.max(42,Math.min(W,H)*.14);x.strokeStyle='#26233a';x.stroke();x.shadowBlur=8;x.strokeStyle='#ff2fa8';x.lineWidth=4;x.stroke();x.restore();trackPath();x.setLineDash([10,14]);x.lineWidth=2;x.strokeStyle='#5b526f';x.stroke();x.setLineDash([]);
for(const m of marks){x.fillStyle='rgba(3,2,9,.55)';x.beginPath();x.arc(m.x*W,m.y*H,2.3,0,7);x.fill()}for(const s of smoke){x.fillStyle='rgba(195,145,255,'+s.q+')';x.beginPath();x.arc(s.x*W,s.y*H,s.r,0,7);x.fill()}
x.save();x.translate(car.x*W,car.y*H);x.rotate(car.a);x.shadowBlur=14;x.shadowColor='#ff7a18';x.fillStyle='#ff7a18';x.fillRect(-7,-13,14,26);x.fillStyle='#ffe8a0';x.fillRect(-4,-11,8,4);x.restore();
x.font='600 14px system-ui';x.fillStyle='#eee9ff';x.fillText('NEON RACER  0.9',18,28);x.font='12px system-ui';x.fillStyle='#958baa';x.fillText(road?'ASPHALT':'OFF ROAD • LOW GRIP',18,46);x.textAlign='right';x.fillStyle='#eee9ff';x.font='600 12px system-ui';x.fillText('AUTO GAS • 2× TAP = DRIFT',W-18,29);x.textAlign='left';
x.globalAlpha=.38;x.fillStyle='#3c3355';x.fillRect(0,H*.64,W*.49,H*.36);x.fillRect(W*.51,H*.64,W*.49,H*.36);x.globalAlpha=1;x.fillStyle='#fff';x.textAlign='center';x.font='24px system-ui';x.fillText('‹',W*.24,H*.84);x.fillText('›',W*.76,H*.84);if(drift>0){x.font='700 13px system-ui';x.fillText('DRIFT',W*.5,H*.58)}x.textAlign='left'}
let last=performance.now();function loop(now){let dt=Math.min((now-last)/1000,.033);last=now,{st,gas,br}=controls(),road=onRoad(),accel=(road?.36:.18)*tune.accel,drag=(road?.42:1.65)*tune.grip,max=(road?.245:.105)*tune.speed;car.s+=gas*accel*dt;car.s-=br*.62*dt;car.s-=car.s*drag*dt;car.s=Math.max(0,Math.min(max,car.s));if(Math.abs(st)>.1)steerHold=Math.min(1.2,steerHold+dt);else steerHold=0;if(car.s>.005){let speedRatio=car.s/max;let steerRate=(road?3.05:1.65)*(1-.34*speedRatio);let turn=st*steerRate*tune.steer;if(drift>0){turn+=driftDir*2.15*tune.drift;car.s*=1-.22*dt;drift=Math.max(0,drift-dt)}car.a+=turn*dt}car.x+=Math.sin(car.a)*car.s*dt;car.y-=Math.cos(car.a)*car.s*dt;car.x=Math.max(.02,Math.min(.98,car.x));car.y=Math.max(.04,Math.min(.96,car.y));let naturalSlip=drift<=0&&steerHold>.32&&Math.abs(st)>.5&&car.s>max*.72;if((naturalSlip||drift>0)&&car.s>.1&&Math.random()<(drift>0?.98:.38))marks.push({x:car.x,y:car.y});if(marks.length>4500)marks.shift();if((naturalSlip||drift>0)&&car.s>.085&&Math.random()<(drift>0?.7:.14))smoke.push({x:car.x,y:car.y,r:3+Math.random()*5,q:.22});for(const s of smoke){s.r+=10*dt;s.q-=.18*dt}smoke=smoke.filter(s=>s.q>0);updateAudio(road,st,br);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);