const c=document.querySelector('#g'),x=c.getContext('2d');let W,H,dpr,car={x:.5,y:.78,a:Math.PI,s:0},keys={},marks=[],smoke=[],mode=1,touches=[],steerOrigin=null;
const modes=['4 BUTTON','STEER + THROTTLE','SMART THROTTLE'];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>keys[e.key]=1);addEventListener('keyup',e=>keys[e.key]=0);
function setTouches(e){e.preventDefault();touches=[...e.touches].map(t=>({x:t.clientX,y:t.clientY,id:t.identifier}));if(!touches.some(t=>t.x<W*.5))steerOrigin=null}
c.addEventListener('touchstart',e=>{let t=e.changedTouches[0];if(t.clientX<W*.5&&!steerOrigin)steerOrigin={x:t.clientX,y:t.clientY,id:t.identifier};setTouches(e)},{passive:false});c.addEventListener('touchmove',setTouches,{passive:false});c.addEventListener('touchend',setTouches,{passive:false});
function trackPath(){x.beginPath();x.moveTo(W*.22,H*.68);x.bezierCurveTo(W*.08,H*.52,W*.12,H*.2,W*.32,H*.18);x.bezierCurveTo(W*.48,H*.13,W*.49,H*.37,W*.61,H*.31);x.bezierCurveTo(W*.77,H*.2,W*.91,H*.29,W*.87,H*.48);x.bezierCurveTo(W*.84,H*.62,W*.66,H*.55,W*.69,H*.72);x.bezierCurveTo(W*.71,H*.88,W*.42,H*.9,W*.22,H*.68)}
function onRoad(){let oc=document.createElement('canvas');oc.width=W;oc.height=H;let q=oc.getContext('2d');q.beginPath();q.moveTo(W*.22,H*.68);q.bezierCurveTo(W*.08,H*.52,W*.12,H*.2,W*.32,H*.18);q.bezierCurveTo(W*.48,H*.13,W*.49,H*.37,W*.61,H*.31);q.bezierCurveTo(W*.77,H*.2,W*.91,H*.29,W*.87,H*.48);q.bezierCurveTo(W*.84,H*.62,W*.66,H*.55,W*.69,H*.72);q.bezierCurveTo(W*.71,H*.88,W*.42,H*.9,W*.22,H*.68);q.lineWidth=Math.max(58,Math.min(W,H)*.105);q.strokeStyle='#fff';q.stroke();return q.getImageData(Math.max(0,Math.min(W-1,car.x*W))|0,Math.max(0,Math.min(H-1,car.y*H))|0,1,1).data[3]>0}
function controls(){let st=0,gas=0,br=0;if(keys.ArrowLeft)st--;if(keys.ArrowRight)st++;if(keys.ArrowUp)gas=1;if(keys.ArrowDown)br=1;
let L=touches.filter(t=>t.x<W*.5),R=touches.filter(t=>t.x>=W*.5);
if(mode===0){for(const t of L)st+=t.x<W*.24?-1:1;for(const t of R)t.y<H*.72?gas=1:br=1}
else{if(L.length&&steerOrigin){let t=L[0];st=Math.max(-1,Math.min(1,(t.x-steerOrigin.x)/55))}
if(mode===1){for(const t of R)t.y<H*.72?gas=1:br=1}else{gas=1;if(R.length){gas=0;br=Math.max(.25,Math.min(1,(R[0].y-H*.45)/(H*.4)))}}}return{st:Math.max(-1,Math.min(1,st)),gas,br}}
function draw(){x.fillStyle='#090615';x.fillRect(0,0,W,H);x.save();x.shadowBlur=22;x.shadowColor='#ff2fa8';trackPath();x.lineWidth=Math.max(58,Math.min(W,H)*.105);x.strokeStyle='#26233a';x.stroke();x.shadowBlur=8;x.strokeStyle='#ff2fa8';x.lineWidth=4;x.stroke();x.restore();trackPath();x.setLineDash([10,14]);x.lineWidth=2;x.strokeStyle='#5b526f';x.stroke();x.setLineDash([]);
for(const m of marks){x.fillStyle='rgba(3,2,9,.55)';x.beginPath();x.arc(m.x*W,m.y*H,2.3,0,7);x.fill()}for(const s of smoke){x.fillStyle='rgba(195,145,255,'+s.q+')';x.beginPath();x.arc(s.x*W,s.y*H,s.r,0,7);x.fill()}
x.save();x.translate(car.x*W,car.y*H);x.rotate(car.a);x.shadowBlur=14;x.shadowColor='#ff7a18';x.fillStyle='#ff7a18';x.fillRect(-7,-13,14,26);x.fillStyle='#ffe8a0';x.fillRect(-4,-11,8,4);x.restore();
x.font='600 14px system-ui';x.fillStyle='#eee9ff';x.fillText('NEON RACER  0.3',18,28);x.font='12px system-ui';x.fillStyle='#958baa';x.fillText(onRoad()?'ASPHALT':'OFF ROAD • LOW GRIP',18,46);
x.textAlign='right';x.fillStyle='#eee9ff';x.font='600 12px system-ui';x.fillText('AUTO GAS',W-18,29);x.textAlign='left';
x.globalAlpha=.45;x.fillStyle='#3c3355';x.fillRect(0,H*.64,W*.34,H*.36);x.fillRect(W*.36,H*.64,W*.28,H*.36);x.fillRect(W*.66,H*.64,W*.34,H*.36);x.globalAlpha=1;x.fillStyle='#fff';x.textAlign='center';x.font='24px system-ui';x.fillText('‹',W*.17,H*.84);x.fillText('›',W*.83,H*.84);x.font='11px system-ui';x.fillText('BRAKE',W*.5,H*.84);x.textAlign='left'}
let last=performance.now();function loop(now){let dt=Math.min((now-last)/1000,.033);last=now,{st,gas,br}=controls(),road=onRoad();let accel=road?.36:.18,drag=road?.42:1.65,max=road?.29:.115;car.s+=gas*accel*dt;car.s-=br*.62*dt;car.s-=car.s*drag*dt;car.s=Math.max(-.07,Math.min(max,car.s));if(Math.abs(car.s)>.005)car.a+=st*(road?2.65:1.75)*dt*(car.s>=0?1:-1);car.x+=Math.sin(car.a)*car.s*dt;car.y-=Math.cos(car.a)*car.s*dt;car.x=Math.max(.02,Math.min(.98,car.x));car.y=Math.max(.04,Math.min(.96,car.y));if(Math.abs(st)>.38&&Math.abs(car.s)>.1&&Math.random()<.7)marks.push({x:car.x,y:car.y});if(marks.length>4500)marks.shift();if((Math.abs(st)>.65||br)&&Math.abs(car.s)>.085&&Math.random()<.28)smoke.push({x:car.x,y:car.y,r:3+Math.random()*5,q:.22});for(const s of smoke){s.r+=10*dt;s.q-=.18*dt}smoke=smoke.filter(s=>s.q>0);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);