const c=document.querySelector('#g'),x=c.getContext('2d');let W,H,dpr,car={x:.25,y:.82,a:0,s:0},keys={},marks=[],smoke=[],touches=[],lastTap={l:0,r:0},drift=0,driftDir=0,steerHold=0,preset=1,audio=null,raceStart=performance.now(),raceOver=false,tune={speed:1,accel:1,steer:1,grip:1,drift:1,offroad:1};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>keys[e.key]=1);addEventListener('keyup',e=>keys[e.key]=0);
async function startAudio(){if(audio){if(audio.A.state==='suspended')await audio.A.resume();return}let A=new (window.AudioContext||window.webkitAudioContext)();await A.resume();let master=A.createGain();master.gain.value=.32;master.connect(A.destination);let eng=A.createOscillator(),eg=A.createGain();eng.type='sawtooth';eng.frequency.value=75;eg.gain.value=.22;eng.connect(eg).connect(master);eng.start();let noise=A.createBufferSource(),buf=A.createBuffer(1,A.sampleRate*2,A.sampleRate);let d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;noise.buffer=buf;noise.loop=true;let filt=A.createBiquadFilter(),ng=A.createGain();filt.type='bandpass';filt.frequency.value=900;filt.Q.value=.7;ng.gain.value=0;noise.connect(filt).connect(ng).connect(master);noise.start();audio={A,eng,eg,ng,filt}}
function updateAudio(road,st,br){if(!audio)return;let t=audio.A.currentTime,s=Math.max(0,car.s);audio.eng.frequency.setTargetAtTime(65+s*520,t,.04);audio.eg.gain.setTargetAtTime(.14+s*.75,t,.04);let slip=Math.max(drift>0?.65:0,Math.abs(st)*Math.max(0,(s-.11)*2.5),road?0:.22);audio.ng.gain.setTargetAtTime(Math.min(.6,slip),t,.025);audio.filt.frequency.setTargetAtTime(road?1100:430,t,.05)}
function setTouches(e){e.preventDefault();touches=[...e.touches].map(t=>({x:t.clientX,y:t.clientY}))}

c.addEventListener('touchstart',e=>{startAudio();let now=performance.now();for(const t of e.changedTouches){let side=t.clientX<W*.36?'l':t.clientX>W*.64?'r':null;if(side){if(now-lastTap[side]<300){drift=.48;driftDir=side==='l'?-1:1}lastTap[side]=now}}setTouches(e)},{passive:false});c.addEventListener('touchmove',setTouches,{passive:false});c.addEventListener('touchend',setTouches,{passive:false});
function trackPath(){x.beginPath();x.moveTo(W*.27,H*.80);x.lineTo(W*.27,H*.30);x.bezierCurveTo(W*.27,H*.18,W*.36,H*.12,W*.50,H*.12);x.bezierCurveTo(W*.66,H*.12,W*.76,H*.19,W*.76,H*.31);x.lineTo(W*.76,H*.48);x.bezierCurveTo(W*.76,H*.55,W*.69,H*.58,W*.61,H*.58);x.lineTo(W*.47,H*.58);x.bezierCurveTo(W*.38,H*.58,W*.37,H*.66,W*.47,H*.69);x.lineTo(W*.68,H*.75);x.bezierCurveTo(W*.82,H*.79,W*.78,H*.90,W*.63,H*.90);x.lineTo(W*.42,H*.90);x.bezierCurveTo(W*.32,H*.90,W*.27,H*.87,W*.27,H*.80)}
let roadCanvas,roadCtx;function roadMask(){if(!roadCanvas||roadCanvas.width!==W||roadCanvas.height!==H){roadCanvas=document.createElement('canvas');roadCanvas.width=W;roadCanvas.height=H;roadCtx=roadCanvas.getContext('2d');roadCtx.clearRect(0,0,W,H);roadCtx.beginPath();roadCtx.moveTo(W*.27,H*.80);roadCtx.lineTo(W*.27,H*.30);roadCtx.bezierCurveTo(W*.27,H*.18,W*.36,H*.12,W*.50,H*.12);roadCtx.bezierCurveTo(W*.66,H*.12,W*.76,H*.19,W*.76,H*.31);roadCtx.lineTo(W*.76,H*.48);roadCtx.bezierCurveTo(W*.76,H*.55,W*.69,H*.58,W*.61,H*.58);roadCtx.lineTo(W*.47,H*.58);roadCtx.bezierCurveTo(W*.38,H*.58,W*.37,H*.66,W*.47,H*.69);roadCtx.lineTo(W*.68,H*.75);roadCtx.bezierCurveTo(W*.82,H*.79,W*.78,H*.90,W*.63,H*.90);roadCtx.lineTo(W*.42,H*.90);roadCtx.bezierCurveTo(W*.32,H*.90,W*.27,H*.87,W*.27,H*.80);roadCtx.lineWidth=Math.max(42,Math.min(W,H)*.14);roadCtx.strokeStyle='#fff';roadCtx.stroke()}}
function onRoad(){roadMask();return roadCtx.getImageData(Math.max(0,Math.min(W-1,car.x*W))|0,Math.max(0,Math.min(H-1,car.y*H))|0,1,1).data[3]>0}
const waypoints=[[.27,.80],[.27,.55],[.27,.30],[.34,.17],[.50,.12],[.68,.18],[.76,.31],[.76,.48],[.66,.57],[.48,.58],[.40,.63],[.48,.69],[.68,.75],[.75,.84],[.63,.90],[.42,.90],[.29,.85]];
let bots=[{x:.29,y:.82,a:0,s:.232,wp:1,lap:1,lane:-.018,wobble:.000,color:'#20e6ff',name:'CYAN'},{x:.25,y:.86,a:0,s:.226,wp:1,lap:1,lane:.018,wobble:2.1,color:'#ff3bd4',name:'PINK'},{x:.29,y:.86,a:0,s:.221,wp:1,lap:1,lane:0,wobble:4.2,color:'#d9ff39',name:'LIME'}];let lap=1,lastFinish=0,finished=[];
function normAng(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}
function updateBots(dt){let now=performance.now()*.001;for(const b of bots){let p=waypoints[b.wp],pn=waypoints[(b.wp+1)%waypoints.length],tx=pn[0]-p[0],ty=pn[1]-p[1],len=Math.hypot(tx,ty)||1,ox=-ty/len*(b.lane+Math.sin(now*.7+b.wobble)*.007),oy=tx/len*(b.lane+Math.sin(now*.7+b.wobble)*.007),dx=p[0]+ox-b.x,dy=p[1]+oy-b.y,target=Math.atan2(dx,-dy),d=normAng(target-b.a);b.a+=Math.max(-3.25*dt,Math.min(3.25*dt,d));let corner=Math.min(.18,Math.abs(d)*.055),targetS=b.s*(1-corner);b.x+=Math.sin(b.a)*targetS*dt;b.y-=Math.cos(b.a)*targetS*dt;if(Math.hypot(dx,dy)<.045){b.wp=(b.wp+1)%waypoints.length;if(b.wp===1)b.lap++}}}
function collide(){for(const b of bots){let dx=car.x-b.x,dy=car.y-b.y,d=Math.hypot(dx*W,dy*H);if(d<17&&d>0){let nx=dx*W/d,ny=dy*H/d,push=(17-d)*.0007;car.x+=nx*push;car.y+=ny*push;b.x-=nx*push*.7;b.y-=ny*push*.7;car.s*=.965;b.a-=normAng(b.a-car.a)*.035}}}
function updateLap(){let near=car.x>.20&&car.x<.34&&car.y>.76&&car.y<.84,now=performance.now();if(near&&Math.sin(car.a)>-.65&&now-lastFinish>5000){if(lastFinish){lap++;if(lap>5&&!raceOver){raceOver=true;finished.push({name:'YOU',t:now-raceStart})}}lastFinish=now}}
function drawBot(b){x.save();x.translate(b.x*W,b.y*H);x.rotate(b.a);x.shadowBlur=10;x.shadowColor=b.color;x.fillStyle='#08070d';x.fillRect(-8,-9,3,8);x.fillRect(5,-9,3,8);x.fillRect(-8,5,3,8);x.fillRect(5,5,3,8);x.fillStyle=b.color;x.beginPath();x.moveTo(-6,-13);x.lineTo(6,-13);x.lineTo(7,10);x.lineTo(4,13);x.lineTo(-4,13);x.lineTo(-7,10);x.closePath();x.fill();x.fillStyle='#21192b';x.fillRect(-4.5,-4,9,8);x.restore()}
function controls(){let st=(keys.ArrowLeft?-1:0)+(keys.ArrowRight?1:0);for(const t of touches){if(t.x<W*.5)st-=1;else st+=1}return{st:Math.max(-1,Math.min(1,st)),gas:1,br:0}}
function drawCar(st,road){let speedN=Math.min(1,car.s/.245),steerVis=st*.42,roll=-st*(.6+speedN*1.15)*Math.min(1,steerHold*2.2),bob=road?Math.sin(performance.now()*.018)*.22*speedN:Math.sin(performance.now()*.045)*1.15*speedN;x.save();x.translate(car.x*W,car.y*H);x.rotate(car.a);x.translate(roll,bob);x.shadowBlur=13;x.shadowColor='#ff7a18';function wheel(px,py,ang=0){x.save();x.translate(px,py);x.rotate(ang);x.fillStyle='#09070d';x.fillRect(-2.1,-4.4,4.2,8.8);x.restore()}wheel(-7,-8,steerVis);wheel(7,-8,steerVis);wheel(-7,8);wheel(7,8);x.fillStyle='#ff7a18';x.beginPath();x.moveTo(-6,-13);x.lineTo(6,-13);x.lineTo(7.5,9);x.lineTo(5,13);x.lineTo(-5,13);x.lineTo(-7.5,9);x.closePath();x.fill();x.shadowBlur=0;x.fillStyle='#ffb347';x.fillRect(-4.7,-10.5,9.4,4.4);x.fillStyle='#24182d';x.fillRect(-4.8,-4.2,9.6,7.8);x.fillStyle='#ffd37a';x.fillRect(-4.5,5,9,3.5);x.fillStyle='rgba(255,255,255,.65)';x.fillRect(-4.6,-11.4,2.5,1.5);x.fillRect(2.1,-11.4,2.5,1.5);x.restore()}
function draw(){let road=onRoad();x.fillStyle='#090615';x.fillRect(0,0,W,H);x.save();x.shadowBlur=22;x.shadowColor='#ff2fa8';trackPath();x.lineWidth=Math.max(42,Math.min(W,H)*.14);x.strokeStyle='#26233a';x.stroke();x.shadowBlur=8;x.strokeStyle='#ff2fa8';x.lineWidth=4;x.stroke();x.restore();trackPath();x.setLineDash([10,14]);x.lineWidth=2;x.strokeStyle='#5b526f';x.stroke();x.setLineDash([]);
x.save();x.strokeStyle='#f4efff';x.lineWidth=3;x.beginPath();x.moveTo(W*.20,H*.80);x.lineTo(W*.34,H*.80);x.stroke();x.restore();
for(const m of marks){x.fillStyle='rgba(3,2,9,.55)';x.beginPath();x.arc(m.x*W,m.y*H,2.3,0,7);x.fill()}for(const s of smoke){x.fillStyle='rgba(195,145,255,'+s.q+')';x.beginPath();x.arc(s.x*W,s.y*H,s.r,0,7);x.fill()}
for(const b of bots)drawBot(b);let {st}=controls();drawCar(st,road);
x.font='600 14px system-ui';x.fillStyle='#eee9ff';x.fillText('NEON RACER  0.13',18,28);x.font='12px system-ui';x.fillStyle='#958baa';x.fillText((road?'ASPHALT':'OFF ROAD • LOW GRIP')+'   LAP '+Math.min(lap,5)+'/5',18,46);x.textAlign='right';x.fillStyle='#eee9ff';x.font='600 12px system-ui';x.fillText('AUTO GAS • 2× TAP = DRIFT',W-18,29);x.textAlign='left';
x.globalAlpha=.38;x.fillStyle='#3c3355';x.fillRect(0,H*.64,W*.49,H*.36);x.fillRect(W*.51,H*.64,W*.49,H*.36);x.globalAlpha=1;x.fillStyle='#fff';x.textAlign='center';x.font='24px system-ui';x.fillText('‹',W*.24,H*.84);x.fillText('›',W*.76,H*.84);if(drift>0){x.font='700 13px system-ui';x.fillText('DRIFT',W*.5,H*.58)}x.textAlign='left';if(raceOver){x.fillStyle='rgba(9,6,21,.78)';x.fillRect(W*.12,H*.39,W*.76,H*.18);x.textAlign='center';x.fillStyle='#fff';x.font='800 24px system-ui';x.fillText('FINISH',W*.5,H*.46);x.font='14px system-ui';x.fillText(((performance.now()-raceStart)/1000).toFixed(1)+' s',W*.5,H*.50);x.textAlign='left'}}
let last=performance.now();function loop(now){let dt=Math.min((now-last)/1000,.033);last=now,{st,gas,br}=controls(),road=onRoad();if(!raceOver)updateBots(dt);updateLap();let accel=(road?.36:.18)*tune.accel,drag=(road?.42:1.65)*tune.grip,max=(road?.245:.105)*tune.speed;car.s+=gas*accel*dt;car.s-=br*.62*dt;car.s-=car.s*drag*dt;car.s=Math.max(0,Math.min(max,car.s));if(Math.abs(st)>.1)steerHold=Math.min(1.2,steerHold+dt);else steerHold=0;if(car.s>.005){let speedRatio=car.s/max;let holdBoost=steerHold<.18?.82:steerHold<.45?1:steerHold<.75?1.28:1.58;let steerRate=(road?3.05:1.65)*(1-.22*speedRatio)*holdBoost;let turn=st*steerRate*tune.steer;if(drift>0){turn+=driftDir*2.15*tune.drift;car.s*=1-.22*dt;drift=Math.max(0,drift-dt)}car.a+=turn*dt}car.x+=Math.sin(car.a)*car.s*dt;car.y-=Math.cos(car.a)*car.s*dt;car.x=Math.max(.02,Math.min(.98,car.x));car.y=Math.max(.04,Math.min(.96,car.y));collide();let naturalSlip=drift<=0&&steerHold>.32&&Math.abs(st)>.5&&car.s>max*.72;if((naturalSlip||drift>0)&&car.s>.1&&Math.random()<(drift>0?.98:.38))marks.push({x:car.x,y:car.y});if(marks.length>4500)marks.shift();if((naturalSlip||drift>0)&&car.s>.085&&Math.random()<(drift>0?.7:.14))smoke.push({x:car.x,y:car.y,r:3+Math.random()*5,q:.22});for(const s of smoke){s.r+=10*dt;s.q-=.18*dt}smoke=smoke.filter(s=>s.q>0);updateAudio(road,st,br);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);